### PR TITLE
Fix Idris `postulate` rendering, add test for lots of postulates.

### LINKED ISSUE #200: Idris 2 implementation of `postulate` is broken
Right now, we compile `postulate` in Idris 2 using the `believe_me : a -> b` primitive. For example

```haskell
postulate (["n" .: builtin "Nat"] |- ("P" .: builtin "Type"))
```

compiles to:

```idris
P : (n : Nat) -> Type
P n = believe_me ()
```

This causes problems for unification later down the line. The problem is that `believe_me` actually *computes*, so `P` will always reduce down to `()`, which then makes it impossible to invert to solve for the `n`. This could be fixed by making `P` abstract, but AFAICT idris 2 does not provide facilities for this.

### PR DESCRIPTION
**Pull request by TOTBWF**
We need to use `namespace` along with `export` to make our "postulates" for idris not unfold. This requires a slight tweak to the grammar, which allows us to write postulate blocks instead of single postulates.

I've also added a test that just generates a giant list of postulates.

This fixes #200.

### CODE REVIEW

File: panbench/grammar/src/Panbench/Grammar/Idris.hs [hunk 1]
```diff
@@ -129,15 +135,21 @@ type IdrisPostulateDefnLhs ann = IdrisTelescope () Identity ann
...
 -- unsafe and could lead to segfaults in compiled code, but the alternative is not worth the engineering effort.
 instance Postulate (IdrisDefn ann) (IdrisPostulateDefnLhs ann) where
-  postulate (tele :- RequiredCell _ nm tp) =
-    (tele :- SingleCell () nm (Just tp)) .= "believe_me" <+> "()"
+  postulate lhss =
+    defn $
+    nest 2 $ hardlines $
+    [ "namespace" <+> "Postulate"
+    , "export"
+    , sepDefnsFor lhss \(tele :- RequiredCell _ nm tp) ->
```
Comment (JacquesCarette) [inline panbench/grammar/src/Panbench/Grammar/Idris.hs]: Here, the extra blank line makes sense, since it's a signature-definition pair.

**Review by JacquesCarette — APPROVED** [review]

**Comment by TOTBWF** [comment]
Just rebased with all the rendering changes, @JacquesCarette mind giving this a ✅ once tests pass?
